import 'package:flutter/material.dart';

class EngineeringPage extends StatelessWidget {
  final List<Map<String, dynamic>> _universities = [
    {
      'name': 'Misr University for Science and Technology (MUST)',
      'location': '6th of October City',
      'minGrade': 75,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'MSA University',
      'location': '6th of October City',
      'minGrade': 75,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'Nile University (NU)',
      'location': 'Sheikh Zayed City',
      'minGrade': 80,
      'credits': 174,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
        'Nanotechnology Engineering',
      ],
    },
    {
      'name': '6th of October University (O6U)',
      'location': '6th of October City',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'The British University in Egypt (BUE)',
      'location': 'El Sherouk City',
      'minGrade': 80,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'Delta University for Science and Technology',
      'location': 'Mansoura',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'The American University in Cairo (AUC)',
      'location': 'Tahrir Square',
      'minGrade': 85,
      'credits': 140,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communications Engineering',
        'Mechanical Engineering',
        'Materials Science and Engineering',
        'Construction Engineering',
        'Environmental Engineering',
        'Computer Science and Engineering',
        'Biomedical Engineering',
        'Nanotechnology Engineering',
        'Energy Engineering',
      ],
    },
    {
      'name': 'Assiut University',
      'location': 'Assiut',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'Badr University in Cairo (BUC)',
      'location': 'Cairo',
      'minGrade': 75,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'German University in Cairo (GUC)',
      'location': 'New Cairo',
      'minGrade': 80,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communications Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Automotive Engineering',
        'Energy Engineering',
        'Materials Science and Engineering',
        'Biomedical Engineering',
        'Computer and Communications Engineering',
      ],
    },
    {
      'name': 'Modern University for Technology and Information (MTI)',
      'location': 'Cairo',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'Pharos University in Alexandria (PUA)',
      'location': 'Alexandria',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'Mustaqbal University',
      'location': 'New Cairo',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
    {
      'name': 'Misr International University (MIU)',
      'location': 'New Cairo',
      'minGrade': 70,
      'credits': 162,
      'majors': [
        'Architectural Engineering',
        'Civil Engineering',
        'Electronics and Communication Engineering',
        'Mechanical Engineering',
        'Mechatronics Engineering',
        'Petroleum Engineering',
        'Computer Engineering',
        'Biomedical Engineering',
        'Renewable Energy Engineering',
        'Materials Engineering',
      ],
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Engineering'),
      ),
      body: ListView.builder(
        itemCount: _universities.length,
        itemBuilder: (context, index) {
          final university = _universities[index];
          return Card(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    university['name'],
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  SizedBox(height: 8),
                  Text('Location: ${university['location']}'),
                  SizedBox(height: 8),
                  Text('Minimum grade to join: ${university['minGrade']}'),
                  SizedBox(height: 8),
                  Text('Credit hours required: ${university['credits']}'),
                  SizedBox(height: 8),
                  Text('Majors offered:'),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: university['majors']
                        .map<Widget>((major) => Text('- $major'))
                        .toList(),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
